
<PKOSRoot>:
  
  BoxLayout:
    pos: root.pos
    size_hint: (None, None)
    size: root.size

    orientation: 'vertical' 
    padding: [space_s]
    spacing: space_s

    canvas.before:
      PushMatrix:
      Color:
        rgba: bg_dark
      Rectangle:
        pos: self.pos
        size: self.size
      PopMatrix:


    ContextTabRow:
      id: context_tabs
      size_hint: (1, .03)


    ContextView:
      id: context_view
      size_hint: (1, .95)

